apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: nodePort
  ports: 
    - port: 80
      #tagertPort: 80
      nodePort: 30000
  selector:
    app: portal-noticias
