apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: primeiro-pod
spec:
  container:
    - name: container-pod-1
      image: nginx:latest
      ports:
        - containerPort: 80